"""Add new table for app1..

Revision ID: 65184e1ee11e
Revises: 6e0bdee8efd9
Create Date: 2025-01-31 09:58:33.683919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65184e1ee11e'
down_revision: Union[str, None] = '6e0bdee8efd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
